CocktailMagician/CocktailMagician.Web/Areas/Admin/Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CocktailMagician.Data;
using CocktailMagician.Data.Models;
using CocktailMagician.Services.Contracts;
using CocktailMagician.Web.ViewModelMappers.Contracts;
using CocktailMagician.Services.DTOs;
using CocktailMagician.Web.Models;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using CocktailMagician.Web.Areas.Admin.Models;
using CocktailMagician.Services.Providers;
using CocktailMagician.Web.Utilities.Constants;
using NToastNotify;

namespace CocktailMagician.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class IngredientsController : Controller
    {
        private readonly IIngredientService service;
        private readonly IViewModelMapper<IngredientDTO, IngredientViewModel> mapper;
        private readonly IImageStorageProvider imageStorage;
        private readonly IToastNotification toastNotification;

        public IngredientsController(IIngredientService service, IViewModelMapper<IngredientDTO,
            IngredientViewModel> mapper, IImageStorageProvider imageStorage, IToastNotification toastNotification)
        {
            this.service = service;
            this.mapper = mapper;
            this.imageStorage = imageStorage;
            this.toastNotification = toastNotification;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            try
            {
                var ingredients = await this.service.GetAllIngredientsAsync(page);

                var ingredientViews = this.mapper.MapToViewModel(ingredients);

                return View(ingredientViews);

            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            try
            {
                var ingredient = await this.service.GetIngredientAsync(id.Value);

                var ingredientViewModel = this.mapper.MapToViewModel(ingredient);

                return View(ingredientViewModel);

            }
            catch (Exception)
            {
                return NotFound();
            }

        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] IngredientCreationViewModel creationModel)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    if (creationModel.File != null)
                    {
                        var imagePath = await this.imageStorage.StoreImage(creationModel.File, "ingredients");
                        creationModel.IngredientViewModel.ImgPath = imagePath;
                    }
                    else
                    {
                        creationModel.IngredientViewModel.ImgPath = ConstantsHolder.DefaultIngredientsImg;
                    }
                    var ingredientDTO = this.mapper.MapToDTO(creationModel.IngredientViewModel);
                    var ingredient = await this.service.CreateIngredientAsync(ingredientDTO);

                    var ingredientViewModel = this.mapper.MapToViewModel(ingredient);
                    this.toastNotification.AddSuccessToastMessage(ConstantsHolder.IngredientCreated);
                    return RedirectToAction("Index");
                }
                catch (ArgumentException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.IngredientExists);
                    return View(creationModel);
                }
                catch (InvalidDataException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.InvalidFiletype);
                    return View(creationModel);
                }
            }
            this.toastNotification.AddWarningToastMessage(ConstantsHolder.InvalidInput);
            return View(creationModel);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            try
            {

                var ingredient = await this.service.GetIngredientAsync(id.Value);
                var ingredientView = this.mapper.MapToViewModel(ingredient);
                var ingredientEditModel = new IngredientCreationViewModel { IngredientViewModel = ingredientView };

                return View(ingredientEditModel);
            }
            catch (Exception)
            {
                return NotFound();
            }

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind] IngredientCreationViewModel editModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    if (editModel.File != null)
                    {
                        var imagePath = await this.imageStorage.StoreImage(editModel.File, "ingredients");
                        editModel.IngredientViewModel.ImgPath = imagePath;
                    }
                    var ingredientDTO = this.mapper.MapToDTO(editModel.IngredientViewModel);
                    var ingredient = await this.service.EditIngredientAsync(ingredientDTO);
                    editModel.IngredientViewModel = this.mapper.MapToViewModel(ingredient);
                    this.toastNotification.AddSuccessToastMessage(ConstantsHolder.IngredientEdited);
                    return RedirectToAction(nameof(Index));
                }
                catch (ArgumentException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.IngredientExists);
                    return View(editModel);
                }
                catch (InvalidDataException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.InvalidFiletype);
                    return View(editModel);
                }
            }
            this.toastNotification.AddWarningToastMessage(ConstantsHolder.InvalidInput);
            return View(editModel);
        }


        public async Task<IActionResult> Delete(Guid? id)
        {
            try
            {
                var ingredient = await this.service.GetIngredientAsync(id.Value);
                var ingredientView = this.mapper.MapToViewModel(ingredient);
                return View(ingredientView);
            }
            catch (Exception)
            {
                return NotFound();
            }

        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var result = await this.service.DeleteIngredientAsync(id);
            if (result)
                this.toastNotification.AddSuccessToastMessage(ConstantsHolder.IngredientDeleted);
            else
                this.toastNotification.AddErrorToastMessage(ConstantsHolder.IngredientNotDeleted);
            return RedirectToAction(nameof(Index));
        }

    }
}

CocktailMagician/CocktailMagician.Web/Controllers/CocktailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CocktailMagician.Data;
using CocktailMagician.Data.Models;
using CocktailMagician.Web.ViewModelMappers.Contracts;
using CocktailMagician.Services.Contracts;
using CocktailMagician.Services.DTOs;
using CocktailMagician.Web.Models;
using CocktailMagician.Services.Providers;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using CocktailMagician.Web.Utilities.Constants;
using NToastNotify;
using Microsoft.VisualBasic;

namespace CocktailMagician.Web.Controllers
{
    public class CocktailsController : Controller
    {
        private readonly ICocktailService service;
        private readonly IIngredientService ingredientService;
        private readonly IViewModelMapper<CocktailDTO, CocktailViewModel> mapper;
        private readonly IViewModelMapper<IngredientDTO, IngredientViewModel> ingredientMapper;
        private readonly IImageStorageProvider imageStorage;
        private readonly IToastNotification toastNotification;

        public CocktailsController(ICocktailService service, IIngredientService ingredientService,
            IViewModelMapper<CocktailDTO, CocktailViewModel> mapper, IViewModelMapper<IngredientDTO, IngredientViewModel> ingredientMapper,
            IImageStorageProvider imageStorage, IToastNotification toastNotification)
        {
            this.service = service;
            this.ingredientService = ingredientService;
            this.mapper = mapper;
            this.ingredientMapper = ingredientMapper;
            this.imageStorage = imageStorage;
            this.toastNotification = toastNotification;
        }

        public async Task<IActionResult> Index(string filterOption, string sortOption, int page = 1)
        {
            PageTransferInfo<CocktailDTO> cocktails;
            ViewBag.CurrentFilter = filterOption;
            ViewBag.CurrentSort = sortOption;
            ViewBag.SortByName = sortOption == "name" ? "name_desc" : "name";
            ViewBag.SortByRating = sortOption == "rating" ? "rating_desc" : "rating";
            if (!String.IsNullOrEmpty(filterOption))
            {
                cocktails = await this.service.FilterCocktailsAsync(filterOption, page);
            }
            else if (!String.IsNullOrEmpty(sortOption))
            {
                cocktails = await this.service.SortCocktailsAsync(sortOption, page);
            }
            else
            {
                cocktails = await this.service.GetAllCocktailsAsync(page);
            }
            var cocktailsViewModel = this.mapper.MapToViewModel(cocktails);


            return View(cocktailsViewModel);
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            try
            {
                var cocktail = await this.service.GetCocktailAsync(id.Value);

                var cocktailViewModel = this.mapper.MapToViewModel(cocktail);

                return View(cocktailViewModel);

            }
            catch (Exception)
            {
                return NotFound();
            }
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create()
        {
            var ingredients = await this.ingredientService.GetAllIngredientsAsync(1, int.MaxValue);
            var ingredientViews = ingredientMapper.MapToViewModel(ingredients);
            var cocktailCreationViewModel = new CocktailCreationViewModel { AllIngredients = ingredientViews.Collection };
            return View(cocktailCreationViewModel);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] CocktailCreationViewModel cocktailCreationViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (cocktailCreationViewModel.File != null)
                    {
                        var imagePath = await this.imageStorage.StoreImage(cocktailCreationViewModel.File, "cocktails");
                        cocktailCreationViewModel.ImgPath = imagePath;
                    }
                    else
                    {
                        cocktailCreationViewModel.ImgPath = ConstantsHolder.DefaultCocktailImg;
                    }
                    var cocktailViewModel = new CocktailViewModel
                    {
                        Name = cocktailCreationViewModel.Name,
                        Description = cocktailCreationViewModel.Description,
                        ImgPath = cocktailCreationViewModel.ImgPath,
                        Ingredients = cocktailCreationViewModel.IngredientIds
                            .Select(x => new IngredientViewModel { Id = x }).ToList()
                    };
                    var cocktailDTO = this.mapper.MapToDTO(cocktailViewModel);
                    var cocktail = await this.service.CreateCocktailAsync(cocktailDTO);

                    cocktailViewModel = this.mapper.MapToViewModel(cocktail);
                    this.toastNotification.AddSuccessToastMessage(ConstantsHolder.CreatedCocktail);
                    return RedirectToAction(nameof(Index));
                }
                catch (ArgumentException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.CocktailExists);
                    return View(cocktailCreationViewModel);
                }
                catch (InvalidDataException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.InvalidFiletype);
                    return View(cocktailCreationViewModel);
                }
            }
            this.toastNotification.AddWarningToastMessage(ConstantsHolder.InvalidInput);
            return View(cocktailCreationViewModel);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            try
            {
                var cocktail = await this.service.GetCocktailAsync(id.Value);

                var cocktailViewModel = this.mapper.MapToViewModel(cocktail);

                var cocktailEditViewModel = new CocktailEditViewModel { Cocktail = cocktailViewModel };

                return View(cocktailEditViewModel);

            }
            catch (Exception)
            {
                return NotFound();
            }
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind] CocktailEditViewModel cocktailEditViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (cocktailEditViewModel.File != null)
                    {
                        var imagePath = await this.imageStorage.StoreImage(cocktailEditViewModel.File, "cocktails");
                        cocktailEditViewModel.Cocktail.ImgPath = imagePath;
                    }

                    var cocktailDTO = this.mapper.MapToDTO(cocktailEditViewModel.Cocktail);
                    var cocktail = await this.service.EditCocktailAsync(cocktailDTO);
                    var cocktailViewModel = this.mapper.MapToViewModel(cocktailDTO);
                    this.toastNotification.AddSuccessToastMessage(ConstantsHolder.CocktailEdited);
                    return RedirectToAction(nameof(Index));
                }
                catch (ArgumentException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.CocktailExists);
                    return View(cocktailEditViewModel);
                }
                catch (InvalidDataException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.InvalidFiletype);
                    return View(cocktailEditViewModel);
                }
            }
            this.toastNotification.AddWarningToastMessage(ConstantsHolder.InvalidInput);
            return View(cocktailEditViewModel);
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> EditIngredients(Guid? id)
        {
            try
            {
                var cocktail = await this.service.GetCocktailAsync(id.Value);

                var cocktailViewModel = this.mapper.MapToViewModel(cocktail);

                var ingredients = await this.ingredientService.GetAllIngredientsAsync(1, int.MaxValue);
                var ingredientViews = ingredientMapper.MapToViewModel(ingredients);
                var creationModel = new CocktailCreationViewModel
                {
                    Name = cocktailViewModel.Name,
                    Id = cocktailViewModel.Id,
                    ImgPath = cocktailViewModel.ImgPath,
                    Description = cocktailViewModel.Description,
                    AllIngredients = ingredientViews.Collection,
                    IngredientIds = cocktailViewModel.Ingredients.Select(c => c.Id).ToList()
                };
                return View(creationModel);

            }
            catch (Exception)
            {
                return NotFound();
            }
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditIngredients([Bind] CocktailCreationViewModel cocktailCreationViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var cocktailViewModel = new CocktailViewModel
                    {
                        Name = cocktailCreationViewModel.Name,
                        Description = cocktailCreationViewModel.Description,
                        ImgPath = cocktailCreationViewModel.ImgPath,

CocktailMagician/CocktailMagician.Web/Areas/Admin/Views/Ingredients/Create.cshtml
@using CocktailMagician.Web.Areas.Admin.Models
@model IngredientCreationViewModel

@{
	ViewData["Title"] = "Create";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Ingredient</h4>
<hr style="background-image: linear-gradient(40deg, #FFC107, aquamarine, #FFC107)" />
<div class="row">
	<div class="col-md-4">
		<form enctype="multipart/form-data" asp-action="Create">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="IngredientViewModel.Name" class="control-label"></label>
				<input asp-for="IngredientViewModel.Name" class="form-control" />
				<span asp-validation-for="IngredientViewModel.Name" class="text-danger"></span>
			</div>
			<div class="form-group" enctype="multipart/form-data" >
				<input asp-for="File" type="file" accept="image/*">
				<span asp-validation-for="File"></span>
				<div class="form-group">
					<div class="col-md-10">
					</div>
				</div>
			</div>


			<div class="form-group">
				<input type="submit" value="Create" class="btn btn-warning" />
				<a asp-action="Index" class="btn btn-outline-warning">Back to List</a>
			</div>
		</form>
	</div>
</div>

CocktailMagician/CocktailMagician.Web/Areas/Admin/Views/Ingredients/Delete.cshtml
@model IngredientViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr style="background-image: linear-gradient(40deg, #FFC107, aquamarine, #FFC107)"/>
    <dl class="row" >
        <dt class="col-sm-2">
            <img src="@Url.Content(Model.ImgPath)" style="height:300px; width: 300px;"/>
        </dt>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-warning" />
        <a asp-action="Index" class="btn btn-outline-warning">Back to List</a>
    </form>
</div>

CocktailMagician/CocktailMagician.Web/Areas/Admin/Views/Ingredients/Details.cshtml
@model IngredientViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 align="center">@Html.DisplayFor(model => model.Name)</h1>
<hr style="background-image: linear-gradient(40deg, #FFC107, aquamarine, #FFC107)" />

<div class="row">
    <div class="col-md-6" align="center">
        <dl>
            <dt>
                <img src="@Url.Content(Model.ImgPath)" style="height:300px; width: 300px" />
            </dt>

        </dl>

        <div>
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-warning">Edit</a>
            @if (!Model.Cocktails.Any())
            {
                <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-warning">Delete</a>
            }
        </div>
    </div>

    <div class="col-md-6" style="background-color: lightgoldenrodyellow; overflow:auto; height:300px; ">
        <div style="display: block; width: 70%; margin: auto;  text-align: center; padding: 15px">
            <p style="color:black;font-size: 30px;">Not the ingredient you need?</p>
            <p style="color:black;">We have more tasty ingredients you can explore. You can</p>
            <p>
                <a asp-action="Index" role="button" class="btn" style="border-color: black;
                        background-color:lightgoldenrodyellow; color: black; font-size: 18px">Return to ingredients</a>
            </p>
            <p style="color: black;">and have fun.</p>
        </div>
    </div>
</div>

<hr style="background-image: linear-gradient(40deg, #FFC107, aquamarine, #FFC107)" />

<h3 align="center">Cocktails</h3>
<div class="row" style="align-content:center">
    @foreach (var item in Model.Cocktails)
    {
        <div class="col-sm-3 col-md-3">
            <div class="thumbnail" style="margin: 10px 0px;">
                <a asp-action="Details" asp-controller="Cocktails" asp-area="" asp-route-id="@item.Id">
                    <img src="@Url.Content(item.ImgPath)" style="height:150px; width: 150px;" />
                </a>
                <div>
                    <span style="background-color:lightgoldenrodyellow; opacity:0.8; position:absolute; bottom:10px;
						padding:10px 5px; width:150px; text-align:center; line-height:1.4em">
                        @Html.DisplayFor(modelItem => item.Name)
                    </span>
                </div>
            </div>
        </div>
    }
</div>

CocktailMagician/CocktailMagician.Web/Areas/Admin/Views/Ingredients/Edit.cshtml
@using CocktailMagician.Web.Areas.Admin.Models
@model IngredientCreationViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>@Html.DisplayFor(model => model.IngredientViewModel.Name)</h4>
<hr style="background-image: linear-gradient(40deg, #FFC107, aquamarine, #FFC107)"/>
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="IngredientViewModel.Id" />
            <div class="form-group">
                <label asp-for="IngredientViewModel.Name" class="control-label"></label>
                <input asp-for="IngredientViewModel.Name" class="form-control" />
                <span asp-validation-for="IngredientViewModel.Name" class="text-danger"></span>
            </div>
			<div class="form-group" enctype="multipart/form-data">
				<input asp-for="File" type="file" accept="image/*">
				<span asp-validation-for="File"></span>
				<div class="form-group">
					<div class="col-md-10">
					</div>
				</div>
			</div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-warning" />
                <a asp-action="Index" class="btn btn-outline-warning">Back to List</a>
            </div>
        </form>
    </div>
</div>

CocktailMagician/CocktailMagician.Web/Areas/Admin/Views/Ingredients/Index.cshtml
@using CocktailMagician.Services.Providers
@model PageTransferInfo<IngredientViewModel>

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 align="center">Ingredients</h1>
<hr style="background-image:linear-gradient(40deg, #FFC107, aquamarine, #FFC107)" />

<p align="center">
	<a asp-action="Create" class="btn btn-outline-warning">Create New Ingredient</a>
</p>

<div class="row" style="align-content:center">
	@foreach (var item in Model.Collection)
	{
		<div class="col-sm-2 col-md-2">
			<div class="thumbnail" style="margin: 10px 0px;">
				<a asp-action="Details" asp-route-id="@item.Id">
					<img src="@Url.Content(item.ImgPath)" style="height:160px; width: 160px;" />
				</a>
				<div>
					<span style="background-color:aquamarine; opacity:0.8; position:absolute; bottom:10px;
							padding:10px 5px; width:160px; text-align:center; line-height:1.4em">
						@Html.DisplayFor(modelItem => item.Name)
					</span>
				</div>
			</div>
		</div>
	}
</div>

<div class="row">
	@if (Model.TotalPages > 1)
	{
		<ul class="pagination">
			@if (Model.HasPreviousPage)
			{
				<li class="page-item ">
					<a href="~/Admin/Ingredients?page=@(Model.PageIndex-1)" class="page-link">@(Model.PageIndex - 1)</a>
				</li>
			}
			<li class="page-item ">
				<a href="~/Admin/Ingredients?page=@Model.PageIndex" class="page-link">@Model.PageIndex</a>
			</li>
			@if (Model.HasNextPage)
			{
				<li class="page-item ">
					<a href="~/Admin/Ingredients?page=@(Model.PageIndex+1)" class="page-link">@(Model.PageIndex + 1)</a>
				</li>
			}
		</ul>
	}
</div>