CocktailMagician/CocktailMagician.Web/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CocktailMagician.Data;
using CocktailMagician.Data.Models;
using CocktailMagician.Web.ViewModelMappers.Contracts;
using CocktailMagician.Services.DTOs;
using CocktailMagician.Web.Areas.Admin.Models;
using CocktailMagician.Services.Contracts;
using Microsoft.AspNetCore.Authorization;
using NToastNotify;
using CocktailMagician.Web.Utilities.Constants;

namespace CocktailMagician.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUserService service;
        private readonly IViewModelMapper<UserDTO, UserViewModel> mapper;
        private readonly IToastNotification toastNotification;

        public UsersController(IUserService service, IViewModelMapper<UserDTO, UserViewModel> mapper, IToastNotification toastNotification)
        {
            this.service = service;
            this.mapper = mapper;
            this.toastNotification = toastNotification;
        }

        // GET: Admin/Users
        public async Task<IActionResult> Index()
        {
            var userDTOs = await this.service.GetAllUsersAsync();
            var bannedUserDTOs = await this.service.GetBannedUsersAsync();
            var allUsersViewModel = new AllUsersViewModel();
            allUsersViewModel.AllUsers = mapper.MapToViewModel(userDTOs);
            allUsersViewModel.BannedUsers = mapper.MapToViewModel(bannedUserDTOs);
            return View(allUsersViewModel);
        }
        public async Task<IActionResult> Ban(Guid? id)
        {
            try
            {
                var user = await this.service.GetUserAsync(id.Value);
                var userViewModel = this.mapper.MapToViewModel(user);
                return View(userViewModel);
            }
            catch
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Ban(UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                var result = await this.service.BanUserAsync(user.Id, user.BannedUntil);
                if (result)
                    this.toastNotification.AddSuccessToastMessage(ConstantsHolder.UserBanned);
                else
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.UserNotBanned);
                
                return RedirectToAction("Index");
            }
            this.toastNotification.AddWarningToastMessage(ConstantsHolder.InvalidInput);
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnBan(Guid id)
        {
            var result = await this.service.UnbanUserAsync(id);
            if (result)
                this.toastNotification.AddSuccessToastMessage(ConstantsHolder.UserUnbanned);
            else
                this.toastNotification.AddErrorToastMessage(ConstantsHolder.UserNotUnbanned);

            return RedirectToAction("Index");
        }
    }
}

CocktailMagician/CocktailMagician.Web/Controllers/BarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CocktailMagician.Services.Contracts;
using CocktailMagician.Web.ViewModelMappers.Contracts;
using CocktailMagician.Web.Models;
using CocktailMagician.Services.DTOs;
using CocktailMagician.Services.Providers;
using Microsoft.AspNetCore.Authorization;
using System.IO;
using CocktailMagician.Web.Utilities.Constants;
using NToastNotify;

namespace CocktailMagician.Web.Controllers
{
    public class BarsController : Controller
    {

        private readonly IBarService barService;
        private readonly ICocktailService cocktailService;
        private readonly IViewModelMapper<BarDTO, BarViewModel> viewModelMapper;
        private readonly IViewModelMapper<CocktailDTO, CocktailViewModel> cocktailMapper;
        private readonly IImageStorageProvider imageStorage;
        private readonly IToastNotification toastNotification;

        public BarsController(IBarService barService, ICocktailService cocktailService,
            IViewModelMapper<BarDTO, BarViewModel> viewModelMapper,
            IViewModelMapper<CocktailDTO, CocktailViewModel> cocktailMapper,
            IImageStorageProvider imageStorage, IToastNotification toastNotification)
        {
            this.barService = barService;
            this.cocktailService = cocktailService;
            this.viewModelMapper = viewModelMapper;
            this.cocktailMapper = cocktailMapper;
            this.imageStorage = imageStorage;
            this.toastNotification = toastNotification;
        }

        // GET: Bars
        public async Task<IActionResult> Index(string filterOption, string sortOption, int page = 1)
        {
            PageTransferInfo<BarDTO> bars;
            ViewBag.CurrentFilter = filterOption;
            ViewBag.CurrentSort = sortOption;

            ViewBag.SortByName = sortOption == "name" ? "name_desc" : "name";
            ViewBag.SortByRating = sortOption == "rating" ? "rating_desc" : "rating";
            ViewBag.SortByAddress = sortOption == "address" ? "address_desc" : "address";

            if (!String.IsNullOrEmpty(filterOption))
            {
                bars = await this.barService.FilterBarsAsync(filterOption, page);
            }
            else if (!String.IsNullOrEmpty(sortOption))
            {
                bars = await this.barService.SortBarsAsync(sortOption, page);
            }
            else
            {
                bars = await this.barService.GetAllBarsAsync(page);
            }

            var barsViewModel = this.viewModelMapper.MapToViewModel(bars);

            return View(barsViewModel);
        }

        // GET: Bars/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            try
            {
                var bar = await this.barService.GetBarAsync(id.Value);



                var barViewModel = this.viewModelMapper.MapToViewModel(bar);

                return View(barViewModel);
            }
            catch
            {
                this.toastNotification.AddErrorToastMessage(ConstantsHolder.GeneralErrorMessage);
                return RedirectToAction("Index");
            }
        }

        // GET: Bars/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind] BarCreationViewModel barCreationModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (barCreationModel.File != null)
                    {
                        var imagePath = await this.imageStorage.StoreImage(barCreationModel.File, "bars");
                        barCreationModel.Bar.ImgPath = imagePath;
                    }
                    else
                    {
                        barCreationModel.Bar.ImgPath = ConstantsHolder.DefaultBarImg;
                    }
                    var barDTO = this.viewModelMapper.MapToDTO(barCreationModel.Bar);

                    await this.barService.CreateBarAsync(barDTO);
                    this.toastNotification.AddSuccessToastMessage(ConstantsHolder.CreatedBar);
                    return RedirectToAction(nameof(Index));

                }
                catch (ArgumentException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.BarExists);
                    return View(barCreationModel);
                }
                catch (InvalidDataException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.InvalidFiletype);
                    return View(barCreationModel);
                }
            }
            this.toastNotification.AddWarningToastMessage(ConstantsHolder.InvalidInput);
            return View(barCreationModel);
        }

        // GET: Bars/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            try
            {
                var bar = await this.barService.GetBarAsync(id.Value);

                if (bar == null)
                {
                    return NotFound();
                }

                var barViewModel = this.viewModelMapper.MapToViewModel(bar);
                var barEditModel = new BarCreationViewModel { Bar = barViewModel };
                return View(barEditModel);
            }
            catch
            {
                this.toastNotification.AddErrorToastMessage(ConstantsHolder.GeneralErrorMessage);
                return RedirectToAction("Index");
            }
        }

        // POST: Bars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind] BarCreationViewModel barEditModel)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    if (barEditModel.File != null)
                    {
                        var imagePath = await this.imageStorage.StoreImage(barEditModel.File, "bars");
                        barEditModel.Bar.ImgPath = imagePath;
                    }
                    var newName = barEditModel.Bar.Name;
                    var newDescription = barEditModel.Bar.Description;
                    var newPhone = barEditModel.Bar.Phone;
                    var newAddress = barEditModel.Bar.Address;
                    var imgPath = barEditModel.Bar.ImgPath;
                    await this.barService.EditBarAsync(barEditModel.Bar.Id, newName, newDescription, newPhone, newAddress, imgPath);
                    this.toastNotification.AddSuccessToastMessage(ConstantsHolder.BarEdited);
                    return RedirectToAction(nameof(Index));
                }
                catch (ArgumentNullException)
                {
                    return NotFound();
                }
                catch (ArgumentException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.BarExists);
                    return View(barEditModel);
                }
                catch (InvalidDataException)
                {
                    this.toastNotification.AddErrorToastMessage(ConstantsHolder.InvalidFiletype);
                    return View(barEditModel);
                }
            }
            this.toastNotification.AddWarningToastMessage(ConstantsHolder.InvalidInput);
            return View(barEditModel);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> AddRemoveCocktails(Guid? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            try
            {
                var bar = await this.barService.GetBarAsync(id.Value);

                if (bar == null)
                {
                    return NotFound();
                }

                var barViewModel = this.viewModelMapper.MapToViewModel(bar);
                var cocktails = await this.cocktailService.GetAllCocktailsAsync(1, int.MaxValue);
                var barCocktailsModel = new BarCocktailsViewModel
                {
                    Bar = barViewModel,
                    AllCocktails = cocktails.Collection.Select(c => cocktailMapper.MapToViewModel(c)).ToList()
                };

                return View(barCocktailsModel);
            }
            catch
            {
                this.toastNotification.AddErrorToastMessage(ConstantsHolder.GeneralErrorMessage);
                return RedirectToAction("Index");
            }
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddRemoveCocktails([Bind] BarCocktailsViewModel barCocktailsViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var cocktailViewModels = barCocktailsViewModel.CocktailIds
                        .Select(c => new CocktailViewModel { Id = c }).ToList();
                    barCocktailsViewModel.Bar.Cocktails = cocktailViewModels;

CocktailMagician/CocktailMagician.Web/Views/Shared/_BarCommentPartial.cshtml
@using CocktailMagician.Web.Areas.Member.Models
@model BarCommentViewModel
	<form asp-area="Member" asp-controller="BarComments" asp-action="Create">
		@Html.TextAreaFor(m => m.Text, 4, 125, new { @class = "form-control" })
		<input type="hidden" asp-for="BarId" />
		<input type="submit" value="Add Comment" class="btn btn-warning" />
	</form>

CocktailMagician/CocktailMagician.Web/Views/Shared/_BarRatingPartial.cshtml
@using CocktailMagician.Web.Areas.Member.Models
@model BarRatingViewModel
<form asp-area="Member" asp-controller="BarRatings" asp-action="Create">
	@(Html.Kendo().Rating()
		.Name("Rating")
		.Min(1)
		.Max(5)
		.Value(Model.Rating)
		.Precision("half")
			)
	<input type="hidden" asp-for="BarId" />
	@if (User.Identity.IsAuthenticated)
	{
	<input type="submit" value="Rate" class="btn btn-warning" />
	}
</form>

CocktailMagician/CocktailMagician.Web/Views/Shared/_CocktailCommentPartial.cshtml
@using CocktailMagician.Web.Areas.Member.Models
@model CocktailCommentViewModel
<form asp-area="Member" asp-controller="CocktailComments" asp-action="Create">
	@Html.TextAreaFor(m => m.Text, 4, 125, new { @class = "form-control" })
	<input type="hidden" asp-for="CocktailId" />
	<input type="submit" value="Add Comment" class="btn btn-warning" />
</form>

CocktailMagician/CocktailMagician.Web/Views/Shared/_CocktailRatingPartial.cshtml
@using CocktailMagician.Web.Areas.Member.Models
@model CocktailRatingViewModel
<form asp-area="Member" asp-controller="CocktailRatings" asp-action="Create">
	@(Html.Kendo().Rating()
		.Name("Rating")
		.Min(1)
		.Max(5)
		.Value(Model.Rating)
		.Precision("half")
			)
	<input type="hidden" asp-for="CocktailId" />
	@if (User.Identity.IsAuthenticated)
	{
		<input type="submit" value="Rate" class="btn btn-warning" />
	}
</form>

CocktailMagician/CocktailMagician.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CocktailMagician.Web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link href="https://kendo.cdn.telerik.com/2020.2.513/styles/kendo.bootstrap-v4.min.css" rel="stylesheet" type="text/css" />
	<script src="https://kendo.cdn.telerik.com/2020.2.513/js/jquery.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2020.2.513/js/jszip.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2020.2.513/js/kendo.all.min.js"></script>
	<script src="https://kendo.cdn.telerik.com/2020.2.513/js/kendo.aspnetmvc.min.js"></script>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3" style="background-color:#FFD147">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
					<img src="~/images/cocktail-magician.png" style="width:60px; height:50px" />
				</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<partial name="_LoginPartial" />
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Bars" asp-action="Index">Bars</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Cocktails" asp-action="Index">Cocktails</a>
						</li>
						@if (User.IsInRole("Admin"))
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="Admin" asp-controller="Ingredients" asp-action="Index">Ingredients</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Users</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Bars" asp-action="Deleted">Deleted Bars</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Cocktails" asp-action="Deleted">Deleted Cocktails</a>
							</li>
						}

					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="footer" style="background-color:#FFD147">
		<div class="container">
			&copy; 2020 - Cocktail Magician - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-dark">Privacy</a>
		</div>
	</footer>
	@await Component.InvokeAsync("NToastNotify")
</body>
</html>